### ISSUE TITLE
User not logged out when reload button pressed

### ISSUE THREAD

**Issue by horkko** [genouest/biomaj-watcher#18]
Hi,

I've installed biomaj-watcher and I've noticed that when I log in fromthe interface of biomaj-watcher and I log out it seems to work correctly.
However, if I press the "reload" button from my web browser, it appears that I'm still logged in :(
Have you any clue of that?

Thx
Emmanuel

**Comment by osallou** [comment]
I suppose the token is not removed from local storage, will have a look

**Comment by osallou** [comment]
in fact no, there is no jwt token with biomaj, only standard session login. I checked code and logout is made on server.
Can you check the request on /auth on page reload ? (what is the query answer)

**Comment by horkko** [comment]
Hi,

The problem seem gone now. I cannot reproduce it today ??? with Chrome at least.
However, with Firefox, the problem persists. If I click 'logout' some tabs disappear from the menu, but for example, on bank list tab, the button 'Add New' is displayed and the button 'loggout' is not here anymore :(
So the problem is with Firefox actually

**Comment by osallou** [comment]
cookie management pb with firefox?

**Comment by horkko** [comment]
I removed auth cookie and reload the page. It seems to work ok now.
