### ISSUE TITLE
Server starts but "The resource could not be found"

### ISSUE THREAD

**Issue by markiskander** [genouest/biomaj-watcher#2]
Hey guys,

So I've spent a bit of time and installed biomaj and biomaj-watcher and all their dependencies (mongodb, python venv, etc) and finally got to a point where the server starts properly. I made sure to refer to my global.properties in the seed.py and development.ini.

So when I turn my web browser to the specified IP (where it says serving on http://x.x.x.x:xxxx), it opens a white page saying 404 Not Found - The resource could not be found: http:/0.0.0.0:6543/app/

So I'm just wondering if I missed any steps and if so what do I need to do to get it working?

Thanks

**Comment by osallou** [comment]
Hi, let's analyse step by step:

do you launch it in dev or production mode ?

Did you execute the build install step described in README.md ? in biomajwatcher/webapp:

```
npm install -g bower
bower install
```

This is needed to install javascript dependencies etc...

Did you install, in the virtual environment (prefered but not mandatory), the biomaj-watcher code with:

```
python setup.py install
```

after the _bower_ command

To ease debugging, it is easier to launch in debug mode:

```
pserve development.ini
```

You should get some interesting logs in console. The fact you get a 404 in /app looks like an issue finding the static web pages under webapp/app directory.

Could you also open the developer console of your web browser to see if there are some errors?

**Comment by osallou** [comment]
Could you also test the route:
http://xxx.xxxx/bank

you should get a page with [] ("no bank") or a list of your banks in json format. If this works, pb is definitly a problem accessing static elements.

**Comment by markiskander** [comment]
I added bank to the URL and it returns [ ] in an otherwise empty page. I also did install setup again after the bower command and it says the versions are already there.

This is all happening from development.ini, by the way

**Comment by osallou** [comment]
as you already executed a setup install before the bower command, you need to force the update or uninstall and reinstall

However, looking at the MANIFEST.in file, I see a carriage return that bothers me and may impact install (line 3 should be continuation of line 2)

For your tests I suggests that you first do the following:

```
pip uninstall biomajwatcher   (remove biomajwatcher python installed code)
python setup.py develop       (install in development mode eg link from python lib directory to current directory, I use this mode in my lab)
pserve development.ini  (run in development mode)
```

If this works, I will test tomorrow a fresh new install in non-develop mode to see if the pb really comes from the MANIFEST file.

Else, please give me logs from the console of the pserve command after accessing to URL.

**Comment by osallou** [comment]
By the way, biomajwatcher is optional. You can fully manage biomaj without the watcher via the command-line.

**Comment by markiskander** [comment]
Alright, I'll get on that first thing in the AM (uninstalling and re-installing). I'll let you know how it goes.

Thanks!

**Comment by markiskander** [comment]
Perfect. I did an uninstall and re-install of biomajwatcher like you specified and now the web page opens properly. Thanks for the prompt replies!

**Comment by osallou** [comment]
Fixed documentation
