### ISSUE TITLE
Feature : no date field indicating latest databank download

### ISSUE THREAD

**Issue by OlivierCollin** [genouest/biomaj-watcher#25]
Hello, 
The table shown in BioMAJ Watcher does not indicate the date of the latest bank download. 
This is an important information for any user who whishes to evaluate the freshness of the data available on a site. Is this information available somewhere else ? 
Best regards, 
Olivier

**Comment by osallou** [comment]
we display release, not download data, how date of download is important?

**Comment by OlivierCollin** [comment]
Release numbers are not conveying information about their latest download. For example, the current version of Genbank on GenOuest is 216. I have to go the Genbank repository to see that the latest release is number 221. From a user point of view such a difference between version numbers can be intriguing.

**Comment by osallou** [comment]
Fixed in commit 4dd9dfbb218760ce3c2ab7f84a33f9b286998fb2

**Comment by OlivierCollin** [comment]
Thank you !
