### ISSUE TITLE
Release Properties window doesn't display the correct information

### ISSUE THREAD

**Issue by markiskander** [genouest/biomaj-watcher#5]
Hey guys,

I managed to get BioMAJ and BioMAJ Watcher up and running and I created a new databank, named it alu, and used all the same settings as inside the alu.properties file. It generated a properties file in the right place and everything seemed to be working:

![1](https://cloud.githubusercontent.com/assets/14098761/9668496/7564e786-5247-11e5-98b9-e509925ba5f2.png)

Clicking on alu opens the bank properties as expected:

![2](https://cloud.githubusercontent.com/assets/14098761/9668508/8950c652-5247-11e5-94b0-4330973bb6d4.png)

Now clicking on the little eye next to Release: 2003-11-26 gets me to this page:

![screenshot_2015-09-03_14-14-07](https://cloud.githubusercontent.com/assets/14098761/9668530/9e533c60-5247-11e5-9dd9-6ab798066cf8.png)

Where it seems none of the strings are showing up properly. The back button also doesn't work. Clicking on show format files also gives me similar results:

![screenshot_2015-09-03_14-14-15](https://cloud.githubusercontent.com/assets/14098761/9668591/fe900072-5247-11e5-952d-565fa4d2ca1a.png)

So, any ideas on how to fix?

Thanks!

**Comment by osallou** [comment]
There is an error on server or info received from server. Did you notice any error message on console on server?

Else, you should open the developer console tool of your browser and check Javascript console, for any error, as well as the network tab to find the network http messages exchanged. You may find here an Http error. I would need the details (query/answer) of the messages.

You will need to reload the page.

If interface is reachable from internet, i can have a look.

**Comment by markiskander** [comment]
Hey,

So the console doesn't display any errors. The Javascript console does display these errors when I press on the eye:
![screenshot_2015-09-04_08-37-35](https://cloud.githubusercontent.com/assets/14098761/9684926/521bb2a2-52e0-11e5-92a9-34446c4de556.png)

The interface is local, and also it doesn't give any HTTP errors, just Javascript.

Thanks!

**Comment by osallou** [comment]
ok,
it seems we introduced an error in release template. It was fixed locally but not in repo.... :-(

I will commit in some minutes, in master branch, the fix,. You can simply pull the code (git pull) and restart your server. If you installed code with "python setup.py develop" as per our previous conversation, there is no need to run this command again. With develop, all local code modiciations are taken into account.

**Comment by markiskander** [comment]
Just to confirm: doing a git pull inside the biomaj-watcher directory and then running the python setup.py develop (I ran it again anyway just to make sure) should be enough to update the files, right? I restarted the server and currently getting the same error

**Comment by osallou** [comment]
Git pull on master branch, no need of setup.py develop again. It is exactly
the same error? Can force the refresh of browser to avoid cache?

Le ven. 4 sept. 2015 16:17, markiskander notifications@github.com a
écrit :

**Comment by markiskander** [comment]
Yeah, it was definitely the cache. Sorry about that.

It works perfectly now. Thanks!

**Comment by osallou** [comment]
Thanks for reporting the bug :-)

Le ven. 4 sept. 2015 16:21, markiskander notifications@github.com a
écrit :
