### ISSUE TITLE
"Schedule" tab is never visible

### ISSUE THREAD

**Issue by markiskander** [genouest/biomaj-watcher#8]
Hey again,

So one more issue I'm having: when I'm logged in, the Logout button and username button appear as they should. But I never get a Schedule button at the top. I can access that page by typing in the url #/schedule, though. 

![screenshot from 2015-09-09 13 36 42](https://cloud.githubusercontent.com/assets/14098761/9770825/f999a122-56f7-11e5-9e71-19277dcbf31c.png)

I've also tried it, removing the custom styling, and it still doesn't show up.

Also one more quick question: how does the Search function work? When I search for alu for example it doesn't return a list of results. Is it meant to search for other things instead?

Thanks again,
Mark.

**Comment by osallou** [comment]
Are declared as "admin" in properties ? You need to be admin to access schedule tab.

For search, you need to activatethe elasticsearch property (use_elastic), and of course start the elasticsearch server. When you "update" a bank, it adds some meta data in elasticsearch for the "search" function. If it is not set, you will get nothing (maybe from a graphical point of view I should hide it if property is not set...)

**Comment by osallou** [comment]
error, schedule tab should appears when logged, even if not admin.
I think I have found, but I do not understand why as it works on my side.

**Comment by osallou** [comment]
ok, I have found for the schedule tab. I indeed had the issue, I just usually access it differently. I have fixed and merge the code, you can simply pull the code.

Fixed: a84f3bc59b44340e7da3166bda478e2f81eacc20

**Comment by markiskander** [comment]
Perfect. Thanks again!

**Comment by osallou** [comment]
You re welcome, and thanks for helping us on debug.... We mostly use the
command line, so...

Le jeu. 10 sept. 2015 02:21, markiskander notifications@github.com a
écrit :
